version: '3.8'

networks:
  api-network:
    driver: bridge

volumes:
  mongodb_vol:

services:
  api:
    image: raphaelcastro35/api-desafio_qa:v1
    container_name: 'api_desafioqa'
    networks:
      - api-network
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://rootdesafioqa:SaudeiDdesafioqa@mongodb:27017/saudeiddesafioqa
    ports:
      - "3001:3001"
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    networks:
      - api-network
    environment:
      - MONGO_INITDB_DATABASE=saudeiddesafioqa
      - MONGO_INITDB_ROOT_USERNAME=rootdesafioqa
      - MONGO_INITDB_ROOT_PASSWORD=SaudeiDdesafioqa
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_vol:/data/db
    ports:
      - "27017-27019:27017-27019"